apiVersion: multipath.io/v1
kind: Multipath
metadata:
  name: multipath-sample
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  config:
    defaults:
      user_friendly_names: "yes"
      find_multipaths: "yes"
      path_grouping_policy: "failover"
      path_selector: "round-robin 0"
      path_checker: "tur"
      failback: "immediate"
      rr_weight: "priorities"
      no_path_retry: "queue"
      rr_min_io: "100"
      flush_on_last_del: "yes"
      max_fds: "max"
      checker_timeout: "60"
      fast_io_fail_tmo: "5"
      dev_loss_timeout: "infinity"
    blacklist:
    - devnode: "^(ram|raw|loop|fd|md|dm-|sr|scd|st|dcssblk)[0-9]"
    - devnode: "^hd[a-z]"
    - devnode: "^cciss!c[0-9]d[0-9]*"
    blacklistExceptions:
    - device:
        vendor: "NetApp"
        product: "LUN.*"
    devices:
    - vendor: "NetApp"
      product: "LUN.*"
      path_grouping_policy: "group_by_prio"
      path_selector: "round-robin 0"
      path_checker: "tur"
      features: "1 queue_if_no_path"
      hardware_handler: "1 alua"
      failback: "immediate"
      rr_weight: "priorities"
      no_path_retry: "queue"
      rr_min_io: "128"
      fast_io_fail_tmo: "5"
      dev_loss_timeout: "infinity"
    - vendor: "IBM"
      product: "2107900"
      path_grouping_policy: "group_by_prio"
      path_selector: "round-robin 0"
      path_checker: "tur"
      features: "1 queue_if_no_path"
      hardware_handler: "1 alua"
      failback: "immediate"
      rr_weight: "priorities"
      no_path_retry: "queue"
  updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
  securityContext:
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
    seLinuxOptions:
      type: "spc_t"