apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: test-multipath-operator
  namespace: openshift-marketplace
spec:
  displayName: Test Multipath Operator
  sourceType: grpc
  image: CATALOG_IMG
